name: 06-use-action-in-matrix

on:
  push: { branches: [main] }

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        package: [playground-pypi-package-k, playground-pypi-package-ll]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: install requirements (build)
        run: pip install --no-cache-dir build==1.2.2.post1

      - name: build
        run: pyproject-build
        working-directory: 06-use-action-in-matrix/${{ matrix.package }}

      - name: publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: 06-use-action-in-matrix/${{ matrix.package }}/dist
